var files_dup =
[
    [ "ConcreteOrderBuilder.h", "_concrete_order_builder_8h_source.html", null ],
    [ "Customer.h", "_customer_8h_source.html", null ],
    [ "CustomerCommand.h", "_customer_command_8h_source.html", null ],
    [ "DecorativePot.h", "_decorative_pot_8h_source.html", null ],
    [ "GiftWrapping.h", "_gift_wrapping_8h_source.html", null ],
    [ "IColleague.h", "_i_colleague_8h_source.html", null ],
    [ "IMediator.h", "_i_mediator_8h_source.html", null ],
    [ "Inventory.h", "_inventory_8h_source.html", null ],
    [ "InventoryManager.h", "_inventory_manager_8h_source.html", null ],
    [ "IObserver.h", "_i_observer_8h_source.html", null ],
    [ "ISubject.h", "_i_subject_8h_source.html", null ],
    [ "NurserySystemFacade.h", "_nursery_system_facade_8h_source.html", null ],
    [ "OrderBuilder.h", "_order_builder_8h_source.html", null ],
    [ "OrderDirector.h", "_order_director_8h_source.html", null ],
    [ "Plant.h", "_plant_8h_source.html", null ],
    [ "PlantFactory.h", "_plant_factory_8h_source.html", null ],
    [ "PlantNursery.h", "_plant_nursery_8h_source.html", null ],
    [ "PlantState.h", "_plant_state_8h_source.html", null ],
    [ "Product.h", "_product_8h_source.html", null ],
    [ "ProductBundle.h", "_product_bundle_8h_source.html", null ],
    [ "ProductDecorator.h", "_product_decorator_8h_source.html", null ],
    [ "ProductItem.h", "_product_item_8h_source.html", null ],
    [ "ShoppingCart.h", "_shopping_cart_8h_source.html", null ],
    [ "StaffAction.h", "_staff_action_8h_source.html", null ],
    [ "StaffCommand.h", "_staff_command_8h_source.html", null ],
    [ "StaffCoordinator.h", "_staff_coordinator_8h_source.html", null ],
    [ "StaffGardener.h", "_staff_gardener_8h_source.html", null ],
    [ "StaffManager.h", "_staff_manager_8h_source.html", null ],
    [ "StaffMember.h", "_staff_member_8h_source.html", null ],
    [ "StaffReaction.h", "_staff_reaction_8h_source.html", null ],
    [ "StaffSalesman.h", "_staff_salesman_8h_source.html", null ],
    [ "WaterCommand.h", "_water_command_8h_source.html", null ],
    [ "WateringStrategy.h", "_watering_strategy_8h_source.html", null ],
    [ "WebAPIAdapter.h", "_web_a_p_i_adapter_8h_source.html", null ]
];